PR2 solved, but I need help with console.log
well1791/web-player-1 pull request #10
Opened 2024-08-19 13:39 UTC by Alastor-git-user

PR2 is completed, though I can't use console.log to print the changes in the select button

2024-08-20 19:13 UTC, Alastor-git-user commented
Improving

2024-08-20 19:37 UTC, well1791 requested changes
Please, don't forget to remove the unused styles from `src/app/page.module.css`

2024-08-20 19:37 UTC, well1791 commented on src/app/components/orderButton/orderButton.tsx
> +        onChange={(event) => {
@Alastor-git-user I don't think an `input` make sense here, please use `select` instead

2024-08-20 19:37 UTC, well1791 commented on src/app/components/orderButton/orderButton.tsx
> +//event.target.value
@Alastor-git-user  no need for this comment

2024-08-20 19:37 UTC, well1791 commented on src/app/components/orderButton/orderButton.tsx
> +        <select className={styles.orderButton}>
@Alastor-git-user here, the solution should more like this (I think)

```tsx
<select
	className={styles.orderButton}
  onChange={(event) => {
    setInputValue(event.target.value);
  }}
>
```

2024-08-26 12:07 UTC, well1791 commented on src/app/components/orderButton/orderButton.tsx
> +        onChange={(event) => {
@Alastor-git-user don't forget to remove this input

2024-08-29 10:05 UTC, well1791 approved these changes
great job!! LGTM! (Looks good to me)

2024-09-01 14:48 UTC, Alastor-git-user commented
Everything is just fine.

2024-09-01 14:48 UTC, merged