The Footer section #11 is properly composed of the correct components.
well1791/web-player-1 pull request #12
Opened 2024-09-01 15:40 UTC by Alastor-git-user

page.txs was modified

the folder footer has been created 

footer.modules.css has all the footer's components

Please send me a feedback

2024-09-01 16:54 UTC, well1791 requested changes

2024-09-01 16:54 UTC, well1791 commented on src/app/components/footer/footer.tsx
> +  const [] = useState("");
@Alastor-git-user this line is not necessary, please remove it

2024-09-02 17:35 UTC, Alastor-git-user commented on src/app/components/footer/footer.tsx
> +  const [] = useState("");
ok, I'll do

2024-09-02 17:43 UTC, well1791 approved these changes
LGTM

2024-09-03 17:09 UTC, merged